// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	user "github.com/smallq_class/app/internal/handler/user"
	"github.com/smallq_class/app/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.UserRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sms/get",
				Handler: user.UserGetSMSCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/app"),
		rest.WithTimeout(5000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: user.UserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/app"),
		rest.WithTimeout(5000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)
}
