// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/smallq_class/dao/model"
)

func newSysUserDeptScope(db *gorm.DB, opts ...gen.DOOption) sysUserDeptScope {
	_sysUserDeptScope := sysUserDeptScope{}

	_sysUserDeptScope.sysUserDeptScopeDo.UseDB(db, opts...)
	_sysUserDeptScope.sysUserDeptScopeDo.UseModel(&model.SysUserDeptScope{})

	tableName := _sysUserDeptScope.sysUserDeptScopeDo.TableName()
	_sysUserDeptScope.ALL = field.NewAsterisk(tableName)
	_sysUserDeptScope.UserID = field.NewInt64(tableName, "user_id")
	_sysUserDeptScope.DeptID = field.NewInt64(tableName, "dept_id")

	_sysUserDeptScope.fillFieldMap()

	return _sysUserDeptScope
}

// sysUserDeptScope 角色和部门关联表
type sysUserDeptScope struct {
	sysUserDeptScopeDo sysUserDeptScopeDo

	ALL    field.Asterisk
	UserID field.Int64 // 角色ID
	DeptID field.Int64 // 部门ID

	fieldMap map[string]field.Expr
}

func (s sysUserDeptScope) Table(newTableName string) *sysUserDeptScope {
	s.sysUserDeptScopeDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysUserDeptScope) As(alias string) *sysUserDeptScope {
	s.sysUserDeptScopeDo.DO = *(s.sysUserDeptScopeDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysUserDeptScope) updateTableName(table string) *sysUserDeptScope {
	s.ALL = field.NewAsterisk(table)
	s.UserID = field.NewInt64(table, "user_id")
	s.DeptID = field.NewInt64(table, "dept_id")

	s.fillFieldMap()

	return s
}

func (s *sysUserDeptScope) WithContext(ctx context.Context) *sysUserDeptScopeDo {
	return s.sysUserDeptScopeDo.WithContext(ctx)
}

func (s sysUserDeptScope) TableName() string { return s.sysUserDeptScopeDo.TableName() }

func (s sysUserDeptScope) Alias() string { return s.sysUserDeptScopeDo.Alias() }

func (s sysUserDeptScope) Columns(cols ...field.Expr) gen.Columns {
	return s.sysUserDeptScopeDo.Columns(cols...)
}

func (s *sysUserDeptScope) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysUserDeptScope) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 2)
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["dept_id"] = s.DeptID
}

func (s sysUserDeptScope) clone(db *gorm.DB) sysUserDeptScope {
	s.sysUserDeptScopeDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysUserDeptScope) replaceDB(db *gorm.DB) sysUserDeptScope {
	s.sysUserDeptScopeDo.ReplaceDB(db)
	return s
}

type sysUserDeptScopeDo struct{ gen.DO }

func (s sysUserDeptScopeDo) Debug() *sysUserDeptScopeDo {
	return s.withDO(s.DO.Debug())
}

func (s sysUserDeptScopeDo) WithContext(ctx context.Context) *sysUserDeptScopeDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysUserDeptScopeDo) ReadDB() *sysUserDeptScopeDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysUserDeptScopeDo) WriteDB() *sysUserDeptScopeDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysUserDeptScopeDo) Session(config *gorm.Session) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysUserDeptScopeDo) Clauses(conds ...clause.Expression) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysUserDeptScopeDo) Returning(value interface{}, columns ...string) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysUserDeptScopeDo) Not(conds ...gen.Condition) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysUserDeptScopeDo) Or(conds ...gen.Condition) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysUserDeptScopeDo) Select(conds ...field.Expr) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysUserDeptScopeDo) Where(conds ...gen.Condition) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysUserDeptScopeDo) Order(conds ...field.Expr) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysUserDeptScopeDo) Distinct(cols ...field.Expr) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysUserDeptScopeDo) Omit(cols ...field.Expr) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysUserDeptScopeDo) Join(table schema.Tabler, on ...field.Expr) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysUserDeptScopeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysUserDeptScopeDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysUserDeptScopeDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysUserDeptScopeDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysUserDeptScopeDo) Group(cols ...field.Expr) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysUserDeptScopeDo) Having(conds ...gen.Condition) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysUserDeptScopeDo) Limit(limit int) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysUserDeptScopeDo) Offset(offset int) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysUserDeptScopeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysUserDeptScopeDo) Unscoped() *sysUserDeptScopeDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysUserDeptScopeDo) Create(values ...*model.SysUserDeptScope) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysUserDeptScopeDo) CreateInBatches(values []*model.SysUserDeptScope, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysUserDeptScopeDo) Save(values ...*model.SysUserDeptScope) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysUserDeptScopeDo) First() (*model.SysUserDeptScope, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserDeptScope), nil
	}
}

func (s sysUserDeptScopeDo) Take() (*model.SysUserDeptScope, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserDeptScope), nil
	}
}

func (s sysUserDeptScopeDo) Last() (*model.SysUserDeptScope, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserDeptScope), nil
	}
}

func (s sysUserDeptScopeDo) Find() ([]*model.SysUserDeptScope, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysUserDeptScope), err
}

func (s sysUserDeptScopeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysUserDeptScope, err error) {
	buf := make([]*model.SysUserDeptScope, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysUserDeptScopeDo) FindInBatches(result *[]*model.SysUserDeptScope, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysUserDeptScopeDo) Attrs(attrs ...field.AssignExpr) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysUserDeptScopeDo) Assign(attrs ...field.AssignExpr) *sysUserDeptScopeDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysUserDeptScopeDo) Joins(fields ...field.RelationField) *sysUserDeptScopeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysUserDeptScopeDo) Preload(fields ...field.RelationField) *sysUserDeptScopeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysUserDeptScopeDo) FirstOrInit() (*model.SysUserDeptScope, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserDeptScope), nil
	}
}

func (s sysUserDeptScopeDo) FirstOrCreate() (*model.SysUserDeptScope, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserDeptScope), nil
	}
}

func (s sysUserDeptScopeDo) FindByPage(offset int, limit int) (result []*model.SysUserDeptScope, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysUserDeptScopeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysUserDeptScopeDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysUserDeptScopeDo) Delete(models ...*model.SysUserDeptScope) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysUserDeptScopeDo) withDO(do gen.Dao) *sysUserDeptScopeDo {
	s.DO = *do.(*gen.DO)
	return s
}
