// Code generated by goctl. DO NOT EDIT.
package types

type BaseResp struct {
	Code int         `json:"code"`
	Data interface{} `json:"data"`
	Msg  string      `json:"msg"`
}

type UserGetSMSCodeReq struct {
	Phone  string `json:"phone"`
	Mtehod string `json:"method,options=Check|Login"`
}

type UserLoginReq struct {
	OpenID string `json:"open_id"`
}

type UserRegisterReq struct {
	Phone    string `json:"phone"`
	Name     string `json:"name,optional"`
	Avatar   string `json:"avatar,optional"`
	Code     string `json:"code"`
	Password string `json:"password"`
	OpenID   string `json:"openId,optional"`
}
