// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysJobLog = "sys_job_log"

// SysJobLog 定时任务调度日志表
type SysJobLog struct {
	JobLogID      int64     `gorm:"column:job_log_id;primaryKey;autoIncrement:true;comment:任务日志ID" json:"job_log_id"` // 任务日志ID
	JobID         int64     `gorm:"column:job_id;not null;comment:任务ID" json:"job_id"`                                // 任务ID
	JobName       string    `gorm:"column:job_name;not null;comment:任务名称" json:"job_name"`                            // 任务名称
	JobGroup      string    `gorm:"column:job_group;not null;comment:任务组名" json:"job_group"`                          // 任务组名
	InvokeTarget  string    `gorm:"column:invoke_target;not null;comment:调用目标字符串" json:"invoke_target"`               // 调用目标字符串
	Status        string    `gorm:"column:status;default:0;comment:执行状态（0正常 1失败）" json:"status"`                      // 执行状态（0正常 1失败）
	ExceptionInfo string    `gorm:"column:exception_info;comment:异常信息" json:"exception_info"`                         // 异常信息
	CreateTime    time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`                               // 创建时间
	CostTime      int64     `gorm:"column:cost_time;comment:耗时（毫秒）" json:"cost_time"`                                 // 耗时（毫秒）
}

// TableName SysJobLog's table name
func (*SysJobLog) TableName() string {
	return TableNameSysJobLog
}
