// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUserDeptScope = "sys_user_dept_scope"

// SysUserDeptScope 角色和部门关联表
type SysUserDeptScope struct {
	UserID int64 `gorm:"column:user_id;primaryKey;comment:角色ID" json:"user_id"` // 角色ID
	DeptID int64 `gorm:"column:dept_id;primaryKey;comment:部门ID" json:"dept_id"` // 部门ID
}

// TableName SysUserDeptScope's table name
func (*SysUserDeptScope) TableName() string {
	return TableNameSysUserDeptScope
}
