// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysNoticeUser = "sys_notice_user"

// SysNoticeUser 消息通知关联用户表
type SysNoticeUser struct {
	UserID   int64  `gorm:"column:user_id;primaryKey" json:"user_id"`
	NoticeID int64  `gorm:"column:notice_id;primaryKey" json:"notice_id"`
	Status   string `gorm:"column:status" json:"status"`
}

// TableName SysNoticeUser's table name
func (*SysNoticeUser) TableName() string {
	return TableNameSysNoticeUser
}
