// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysJob = "sys_job"

// SysJob 定时任务调度表
type SysJob struct {
	JobID          int64     `gorm:"column:job_id;primaryKey;autoIncrement:true;comment:任务ID" json:"job_id"` // 任务ID
	JobName        string    `gorm:"column:job_name;not null;comment:任务名称" json:"job_name"`                  // 任务名称
	JobParams      string    `gorm:"column:job_params;comment:参数" json:"job_params"`                         // 参数
	InvokeTarget   string    `gorm:"column:invoke_target;not null;comment:调用目标字符串" json:"invoke_target"`     // 调用目标字符串
	CronExpression string    `gorm:"column:cron_expression;comment:cron执行表达式" json:"cron_expression"`        // cron执行表达式
	Status         string    `gorm:"column:status;default:0;comment:状态（0正常 1暂停）" json:"status"`              // 状态（0正常 1暂停）
	CreateBy       string    `gorm:"column:create_by;comment:创建者" json:"create_by"`                          // 创建者
	CreateTime     time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`                     // 创建时间
	UpdateBy       string    `gorm:"column:update_by;comment:更新者" json:"update_by"`                          // 更新者
	UpdateTime     time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`                     // 更新时间
}

// TableName SysJob's table name
func (*SysJob) TableName() string {
	return TableNameSysJob
}
